spring.application.name=lifelink-backend

# Data Source Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lifelink
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.json_format_mapper=com.lifelink.lifelink.backend.config.Jackson3FormatMapper

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JWT Secret (This should ideally match environment var in prod)
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2b8c9d23194a08da1fecbb6e8b4699053
jwt.expiration=86400000
